development:
  adapter: postgresql
  encoding: unicode
  database: minifast_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: minifast_test
  pool: 5
  username: postgres
  password:
