name: Test and Lint

on: push

# Subsequently queued workflow interrupts previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    env:
      GOOGLE_MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}
      GOOGLE_MAPS_PRIVATE_KEY: ${{ secrets.GOOGLE_MAPS_PRIVATE_KEY }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: RSpec
        run: bundle exec rspec

  lint:
    env:
      GOOGLE_MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}
      GOOGLE_MAPS_PRIVATE_KEY: ${{ secrets.GOOGLE_MAPS_PRIVATE_KEY }}

    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Standard Ruby
        run: bundle exec standardrb  --format github --format "Standard::Formatter"

      - name: License Finder
        run: bundle exec license_finder
